steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ai-marketing-e2b7e/github.com/mahogny-ice/merge-media:latest', '-f', 'Dockerfile', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ai-marketing-e2b7e/github.com/mahogny-ice/merge-media:latest']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'merge-media'
      - '--image'
      - 'gcr.io/ai-marketing-e2b7e/github.com/mahogny-ice/merge-media:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

logs_bucket: 'gs://ai-marketing-e2b7e.appspot.com/logs'